services:
  swift:
    # useful if you need to re-run the tests/spec
    # https://docs.openstack.org/ocata/cli-reference/swift.html
    # manual steps to set environment variables and create container
    # export OS_USERNAME=swift
    # export OS_PASSWORD=fingertips
    # export OS_PROJECT_NAME=service
    # export OS_USER_DOMAIN_NAME=Default
    # export OS_PROJECT_DOMAIN_NAME=Default
    # export OS_AUTH_URL=http://127.0.0.1:35357/v3
    # export OS_IDENTITY_API_VERSION=3
    # swift auth
    # swift post era
    image: kklopfenstein/openstack-swift-keystone-docker
    environment:
      - KS_SWIFT_PUBLIC_URL=http://127.0.0.1:8080
    ports:
      - '8080:8080'
      - '5000:5000'
      - '35357:35357'
    volumes:
     - ./etc/proxy-server.conf:/etc/swift/proxy-server.conf