# create pushmi_pullyu container from source.
# entry point is bash to allow running of rake and other tests by a developer.

FROM ruby:2.3.4

WORKDIR /app/ 

ADD Gemfile /app/
ADD pushmi_pullyu.gemspec /app/
ADD lib/pushmi_pullyu/version.rb /app/lib/pushmi_pullyu/version.rb
ADD . /app
RUN bundle install

CMD ["bash"]
