#!/usr/bin/env ruby

require 'pushmi_pullyu'

begin
  cli = PushmiPullyu::CLI.instance
  cli.parse
  cli.run
rescue => e
  raise e if $DEBUG
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end
